<?php

namespace App\Http\Controllers\ajax;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OptionsController extends Controller
{
    public function index(Request $request)
    {
        $r = $request-all();
        return response()->json($r, 200, [], JSON_PRETTY_PRINT);
    }

    public function city()
    {
        $city = [];
        $city[] = ['id'=>0, 'text'=>''];
        $city[] = ['id'=>1, 'text'=>'基隆市'];
        $city[] = ['id'=>2, 'text'=>'台北市'];
        $city[] = ['id'=>3, 'text'=>'新北市'];
        $city[] = ['id'=>4, 'text'=>'宜蘭縣'];
        $city[] = ['id'=>5, 'text'=>'新竹市'];
        $city[] = ['id'=>6, 'text'=>'新竹縣'];
        $city[] = ['id'=>7, 'text'=>'桃園縣'];
        $city[] = ['id'=>8, 'text'=>'苗栗縣'];
        $city[] = ['id'=>9, 'text'=>'台中市'];
        $city[] = ['id'=>10, 'text'=>'彰化縣'];
        $city[] = ['id'=>11, 'text'=>'南投縣'];
        $city[] = ['id'=>12, 'text'=>'嘉義市'];
        $city[] = ['id'=>13, 'text'=>'嘉義縣'];
        $city[] = ['id'=>14, 'text'=>'雲林縣'];
        $city[] = ['id'=>15, 'text'=>'台南市'];
        $city[] = ['id'=>16, 'text'=>'高雄市'];
        $city[] = ['id'=>17, 'text'=>'屏東縣'];
        $city[] = ['id'=>18, 'text'=>'台東縣'];
        $city[] = ['id'=>19, 'text'=>'花蓮縣'];
        $city[] = ['id'=>20, 'text'=>'金門縣'];
        $city[] = ['id'=>21, 'text'=>'連江縣'];
        $city[] = ['id'=>22, 'text'=>'澎湖縣'];
        $city[] = ['id'=>23, 'text'=>'南海諸島'];
        return response()->json($city, 200, [], JSON_PRETTY_PRINT);
    }

    public function area(Request $request)
    {
        //$attributes = $request->all();
        $city_id = $request->get('q');
        $area = [];
        $area[0][] = ['id'=>0, 'text'=>''];

        $area[1][] = ['id'=>200, 'text'=>'仁愛區'];
        $area[1][] = ['id'=>201, 'text'=>'信義區'];
        $area[1][] = ['id'=>202, 'text'=>'中正區'];
        $area[1][] = ['id'=>203, 'text'=>'中山區'];
        $area[1][] = ['id'=>204, 'text'=>'安樂區'];
        $area[1][] = ['id'=>205, 'text'=>'暖暖區'];
        $area[1][] = ['id'=>206, 'text'=>'七堵區'];

        $area[2][] = ['id'=>100, 'text'=>'中正區'];
        $area[2][] = ['id'=>103, 'text'=>'大同區'];
        $area[2][] = ['id'=>104, 'text'=>'中山區'];
        $area[2][] = ['id'=>105, 'text'=>'松山區'];
        $area[2][] = ['id'=>106, 'text'=>'大安區'];
        $area[2][] = ['id'=>108, 'text'=>'萬華區'];
        $area[2][] = ['id'=>110, 'text'=>'信義區'];
        $area[2][] = ['id'=>111, 'text'=>'士林區'];
        $area[2][] = ['id'=>112, 'text'=>'北投區'];
        $area[2][] = ['id'=>114, 'text'=>'內湖區'];
        $area[2][] = ['id'=>115, 'text'=>'南港區'];
        $area[2][] = ['id'=>116, 'text'=>'文山區'];

        $area[3][] = ['id'=>207, 'text'=>'萬里區'];
        $area[3][] = ['id'=>208, 'text'=>'金山區'];
        $area[3][] = ['id'=>220, 'text'=>'板橋區'];
        $area[3][] = ['id'=>221, 'text'=>'汐止區'];
        $area[3][] = ['id'=>222, 'text'=>'深坑區'];
        $area[3][] = ['id'=>223, 'text'=>'石碇區'];
        $area[3][] = ['id'=>223, 'text'=>'石碇區'];
        $area[3][] = ['id'=>224, 'text'=>'瑞芳區'];
        $area[3][] = ['id'=>226, 'text'=>'平溪區'];
        $area[3][] = ['id'=>227, 'text'=>'雙溪區'];
        $area[3][] = ['id'=>228, 'text'=>'貢寮區'];
        $area[3][] = ['id'=>231, 'text'=>'新店區'];
        $area[3][] = ['id'=>232, 'text'=>'坪林區'];
        $area[3][] = ['id'=>233, 'text'=>'烏來區'];
        $area[3][] = ['id'=>234, 'text'=>'永和區'];
        $area[3][] = ['id'=>235, 'text'=>'中和區'];
        $area[3][] = ['id'=>236, 'text'=>'土城區'];
        $area[3][] = ['id'=>237, 'text'=>'三峽區'];
        $area[3][] = ['id'=>238, 'text'=>'樹林區'];
        $area[3][] = ['id'=>239, 'text'=>'鶯歌區'];
        $area[3][] = ['id'=>241, 'text'=>'三重區'];
        $area[3][] = ['id'=>242, 'text'=>'新莊區'];
        $area[3][] = ['id'=>243, 'text'=>'泰山區'];
        $area[3][] = ['id'=>244, 'text'=>'林口區'];
        $area[3][] = ['id'=>247, 'text'=>'蘆洲區'];
        $area[3][] = ['id'=>248, 'text'=>'五股區'];
        $area[3][] = ['id'=>249, 'text'=>'八里區'];
        $area[3][] = ['id'=>251, 'text'=>'淡水區'];
        $area[3][] = ['id'=>252, 'text'=>'三芝區'];
        $area[3][] = ['id'=>253, 'text'=>'石門區'];

        $area[4][] = ['id'=>260, 'text'=>'宜蘭市'];
        $area[4][] = ['id'=>261, 'text'=>'頭城鎮'];
        $area[4][] = ['id'=>262, 'text'=>'礁溪鄉'];
        $area[4][] = ['id'=>263, 'text'=>'壯圍鄉'];
        $area[4][] = ['id'=>264, 'text'=>'員山鄉'];
        $area[4][] = ['id'=>265, 'text'=>'羅東鎮'];
        $area[4][] = ['id'=>266, 'text'=>'三星鄉'];
        $area[4][] = ['id'=>267, 'text'=>'大同鄉'];
        $area[4][] = ['id'=>268, 'text'=>'五結鄉'];
        $area[4][] = ['id'=>269, 'text'=>'冬山鄉'];
        $area[4][] = ['id'=>270, 'text'=>'蘇澳鎮'];
        $area[4][] = ['id'=>272, 'text'=>'南澳鄉'];
        $area[4][] = ['id'=>290, 'text'=>'釣魚台列嶼'];
        
        $area[5][] = ['id'=>300, 'text'=>'東區'];
        $area[5][] = ['id'=>300, 'text'=>'北區'];
        $area[5][] = ['id'=>300, 'text'=>'香山區'];

        $area[6][] = ['id'=>302, 'text'=>'竹北市'];
        $area[6][] = ['id'=>303, 'text'=>'湖口鄉'];
        $area[6][] = ['id'=>304, 'text'=>'新豐鄉'];
        $area[6][] = ['id'=>305, 'text'=>'新埔鎮'];
        $area[6][] = ['id'=>306, 'text'=>'關西鎮'];
        $area[6][] = ['id'=>307, 'text'=>'芎林鄉'];
        $area[6][] = ['id'=>308, 'text'=>'寶山鄉'];
        $area[6][] = ['id'=>310, 'text'=>'竹東鎮'];
        $area[6][] = ['id'=>311, 'text'=>'五峰鄉'];
        $area[6][] = ['id'=>312, 'text'=>'橫山鄉'];
        $area[6][] = ['id'=>313, 'text'=>'尖石鄉'];
        $area[6][] = ['id'=>314, 'text'=>'北埔鄉'];
        $area[6][] = ['id'=>315, 'text'=>'峨嵋鄉'];
        
        $area[7][] = ['id'=>320, 'text'=>'中壢市'];
        $area[7][] = ['id'=>324, 'text'=>'平鎮市'];
        $area[7][] = ['id'=>325, 'text'=>'龍潭鄉'];
        $area[7][] = ['id'=>326, 'text'=>'楊梅鎮'];
        $area[7][] = ['id'=>327, 'text'=>'新屋鄉'];
        $area[7][] = ['id'=>328, 'text'=>'觀音鄉'];
        $area[7][] = ['id'=>330, 'text'=>'桃園市'];
        $area[7][] = ['id'=>333, 'text'=>'龜山鄉'];
        $area[7][] = ['id'=>334, 'text'=>'八德市'];
        $area[7][] = ['id'=>335, 'text'=>'大溪鎮'];
        $area[7][] = ['id'=>336, 'text'=>'復興鄉'];
        $area[7][] = ['id'=>337, 'text'=>'大園鄉'];
        $area[7][] = ['id'=>338, 'text'=>'蘆竹鄉'];

        $area[8][] = ['id'=>350, 'text'=>'竹南鎮'];
        $area[8][] = ['id'=>351, 'text'=>'頭份鎮'];
        $area[8][] = ['id'=>352, 'text'=>'三灣鄉'];
        $area[8][] = ['id'=>353, 'text'=>'南庄鄉'];
        $area[8][] = ['id'=>354, 'text'=>'獅潭鄉'];
        $area[8][] = ['id'=>356, 'text'=>'後龍鎮'];
        $area[8][] = ['id'=>357, 'text'=>'通霄鎮'];
        $area[8][] = ['id'=>358, 'text'=>'苑裡鎮'];
        $area[8][] = ['id'=>360, 'text'=>'苗栗市'];
        $area[8][] = ['id'=>361, 'text'=>'造橋鄉'];
        $area[8][] = ['id'=>362, 'text'=>'頭屋鄉'];
        $area[8][] = ['id'=>363, 'text'=>'公館鄉'];
        $area[8][] = ['id'=>364, 'text'=>'大湖鄉'];
        $area[8][] = ['id'=>365, 'text'=>'泰安鄉'];
        $area[8][] = ['id'=>366, 'text'=>'銅鑼鄉'];
        $area[8][] = ['id'=>367, 'text'=>'三義鄉'];
        $area[8][] = ['id'=>368, 'text'=>'西湖鄉'];
        $area[8][] = ['id'=>369, 'text'=>'卓蘭鎮'];

        $area[9][] = ['id'=>400, 'text'=>'中區'];
        $area[9][] = ['id'=>401, 'text'=>'東區'];
        $area[9][] = ['id'=>402, 'text'=>'南區'];
        $area[9][] = ['id'=>403, 'text'=>'西區'];
        $area[9][] = ['id'=>404, 'text'=>'北區'];
        $area[9][] = ['id'=>406, 'text'=>'北屯區'];
        $area[9][] = ['id'=>407, 'text'=>'西屯區'];
        $area[9][] = ['id'=>408, 'text'=>'南屯區'];
        $area[9][] = ['id'=>411, 'text'=>'太平區'];
        $area[9][] = ['id'=>412, 'text'=>'大里區'];
        $area[9][] = ['id'=>413, 'text'=>'霧峰區'];
        $area[9][] = ['id'=>414, 'text'=>'烏日區'];
        $area[9][] = ['id'=>420, 'text'=>'豐原區'];
        $area[9][] = ['id'=>421, 'text'=>'后里區'];
        $area[9][] = ['id'=>422, 'text'=>'石岡區'];
        $area[9][] = ['id'=>423, 'text'=>'東勢區'];
        $area[9][] = ['id'=>424, 'text'=>'和平區'];
        $area[9][] = ['id'=>426, 'text'=>'新社區'];
        $area[9][] = ['id'=>427, 'text'=>'潭子區'];
        $area[9][] = ['id'=>428, 'text'=>'大雅區'];
        $area[9][] = ['id'=>429, 'text'=>'神岡區'];
        $area[9][] = ['id'=>432, 'text'=>'大肚區'];
        $area[9][] = ['id'=>433, 'text'=>'沙鹿區'];
        $area[9][] = ['id'=>434, 'text'=>'龍井區'];
        $area[9][] = ['id'=>435, 'text'=>'梧棲區'];
        $area[9][] = ['id'=>436, 'text'=>'清水區'];
        $area[9][] = ['id'=>437, 'text'=>'大甲區'];
        $area[9][] = ['id'=>438, 'text'=>'外埔區'];
        $area[9][] = ['id'=>439, 'text'=>'大安區'];

        $area[10][] = ['id'=>500, 'text'=>'彰化市'];
        $area[10][] = ['id'=>502, 'text'=>'芬園鄉'];
        $area[10][] = ['id'=>503, 'text'=>'花壇鄉'];
        $area[10][] = ['id'=>504, 'text'=>'秀水鄉'];
        $area[10][] = ['id'=>505, 'text'=>'鹿港鎮'];
        $area[10][] = ['id'=>506, 'text'=>'福興鄉'];
        $area[10][] = ['id'=>507, 'text'=>'線西鄉'];
        $area[10][] = ['id'=>508, 'text'=>'和美鎮'];
        $area[10][] = ['id'=>509, 'text'=>'伸港鄉'];
        $area[10][] = ['id'=>510, 'text'=>'員林鎮'];
        $area[10][] = ['id'=>511, 'text'=>'社頭鄉'];
        $area[10][] = ['id'=>512, 'text'=>'永靖鄉'];
        $area[10][] = ['id'=>513, 'text'=>'埔心鄉'];
        $area[10][] = ['id'=>514, 'text'=>'溪湖鎮'];
        $area[10][] = ['id'=>515, 'text'=>'大村鄉'];
        $area[10][] = ['id'=>516, 'text'=>'埔鹽鄉'];
        $area[10][] = ['id'=>520, 'text'=>'田中鎮'];
        $area[10][] = ['id'=>521, 'text'=>'北斗鎮'];
        $area[10][] = ['id'=>522, 'text'=>'田尾鄉'];
        $area[10][] = ['id'=>523, 'text'=>'埤頭鄉'];
        $area[10][] = ['id'=>524, 'text'=>'溪州鄉'];
        $area[10][] = ['id'=>525, 'text'=>'竹塘鄉'];
        $area[10][] = ['id'=>526, 'text'=>'二林鎮'];
        $area[10][] = ['id'=>527, 'text'=>'大城鄉'];
        $area[10][] = ['id'=>528, 'text'=>'芳苑鄉'];
        $area[10][] = ['id'=>530, 'text'=>'二水鄉'];

        $area[11][] = ['id'=>540, 'text'=>'南投市'];
        $area[11][] = ['id'=>541, 'text'=>'中寮鄉'];
        $area[11][] = ['id'=>542, 'text'=>'草屯鎮'];
        $area[11][] = ['id'=>544, 'text'=>'國姓鄉'];
        $area[11][] = ['id'=>545, 'text'=>'埔里鎮'];
        $area[11][] = ['id'=>546, 'text'=>'仁愛鄉'];
        $area[11][] = ['id'=>551, 'text'=>'名間鄉'];
        $area[11][] = ['id'=>552, 'text'=>'集集鎮'];
        $area[11][] = ['id'=>553, 'text'=>'水里鄉'];
        $area[11][] = ['id'=>555, 'text'=>'魚池鄉'];
        $area[11][] = ['id'=>556, 'text'=>'信義鄉'];
        $area[11][] = ['id'=>557, 'text'=>'竹山鎮'];
        $area[11][] = ['id'=>558, 'text'=>'鹿谷鄉'];

        $area[12][] = ['id'=>600, 'text'=>'東區'];
        $area[12][] = ['id'=>600, 'text'=>'西區'];

        $area[13][] = ['id'=>602, 'text'=>'番路鄉'];
        $area[13][] = ['id'=>603, 'text'=>'梅山鄉'];
        $area[13][] = ['id'=>604, 'text'=>'竹崎鄉'];
        $area[13][] = ['id'=>605, 'text'=>'阿里山'];
        $area[13][] = ['id'=>606, 'text'=>'中埔鄉'];
        $area[13][] = ['id'=>607, 'text'=>'大埔鄉'];
        $area[13][] = ['id'=>608, 'text'=>'水上鄉'];
        $area[13][] = ['id'=>611, 'text'=>'鹿草鄉'];
        $area[13][] = ['id'=>612, 'text'=>'太保市'];
        $area[13][] = ['id'=>613, 'text'=>'朴子市'];
        $area[13][] = ['id'=>614, 'text'=>'東石鄉'];
        $area[13][] = ['id'=>615, 'text'=>'六腳鄉'];
        $area[13][] = ['id'=>616, 'text'=>'新港鄉'];
        $area[13][] = ['id'=>621, 'text'=>'民雄鄉'];
        $area[13][] = ['id'=>622, 'text'=>'大林鎮'];
        $area[13][] = ['id'=>623, 'text'=>'溪口鄉'];
        $area[13][] = ['id'=>624, 'text'=>'義竹鄉'];
        $area[13][] = ['id'=>625, 'text'=>'布袋鎮'];

        $area[14][] = ['id'=>630, 'text'=>'斗南鎮'];
        $area[14][] = ['id'=>631, 'text'=>'大埤鄉'];
        $area[14][] = ['id'=>632, 'text'=>'虎尾鎮'];
        $area[14][] = ['id'=>633, 'text'=>'土庫鎮'];
        $area[14][] = ['id'=>634, 'text'=>'褒忠鄉'];
        $area[14][] = ['id'=>635, 'text'=>'東勢鄉'];
        $area[14][] = ['id'=>636, 'text'=>'臺西鄉'];
        $area[14][] = ['id'=>637, 'text'=>'崙背鄉'];
        $area[14][] = ['id'=>638, 'text'=>'麥寮鄉'];
        $area[14][] = ['id'=>640, 'text'=>'斗六市'];
        $area[14][] = ['id'=>643, 'text'=>'林內鄉'];
        $area[14][] = ['id'=>646, 'text'=>'古坑鄉'];
        $area[14][] = ['id'=>647, 'text'=>'莿桐鄉'];
        $area[14][] = ['id'=>648, 'text'=>'西螺鎮'];
        $area[14][] = ['id'=>649, 'text'=>'二崙鄉'];
        $area[14][] = ['id'=>651, 'text'=>'北港鎮'];
        $area[14][] = ['id'=>652, 'text'=>'水林鄉'];
        $area[14][] = ['id'=>653, 'text'=>'口湖鄉'];
        $area[14][] = ['id'=>654, 'text'=>'四湖鄉'];
        $area[14][] = ['id'=>655, 'text'=>'元長鄉'];

        $area[15][] = ['id'=>700, 'text'=>'中西區'];
        $area[15][] = ['id'=>701, 'text'=>'東區'];
        $area[15][] = ['id'=>702, 'text'=>'南區'];
        $area[15][] = ['id'=>704, 'text'=>'北區'];
        $area[15][] = ['id'=>708, 'text'=>'安平區'];
        $area[15][] = ['id'=>709, 'text'=>'安南區'];
        $area[15][] = ['id'=>710, 'text'=>'永康區'];
        $area[15][] = ['id'=>711, 'text'=>'歸仁區'];
        $area[15][] = ['id'=>712, 'text'=>'新化區'];
        $area[15][] = ['id'=>713, 'text'=>'左鎮區'];
        $area[15][] = ['id'=>714, 'text'=>'玉井區'];
        $area[15][] = ['id'=>715, 'text'=>'楠西區'];
        $area[15][] = ['id'=>716, 'text'=>'南化區'];
        $area[15][] = ['id'=>717, 'text'=>'仁德區'];
        $area[15][] = ['id'=>718, 'text'=>'關廟區'];
        $area[15][] = ['id'=>719, 'text'=>'龍崎區'];
        $area[15][] = ['id'=>720, 'text'=>'官田區'];
        $area[15][] = ['id'=>721, 'text'=>'麻豆區'];
        $area[15][] = ['id'=>722, 'text'=>'佳里區'];
        $area[15][] = ['id'=>723, 'text'=>'西港區'];
        $area[15][] = ['id'=>724, 'text'=>'七股區'];
        $area[15][] = ['id'=>725, 'text'=>'將軍區'];
        $area[15][] = ['id'=>726, 'text'=>'學甲區'];
        $area[15][] = ['id'=>727, 'text'=>'北門區'];
        $area[15][] = ['id'=>730, 'text'=>'新營區'];
        $area[15][] = ['id'=>731, 'text'=>'後壁區'];
        $area[15][] = ['id'=>732, 'text'=>'白河區'];
        $area[15][] = ['id'=>733, 'text'=>'東山區'];
        $area[15][] = ['id'=>734, 'text'=>'六甲區'];
        $area[15][] = ['id'=>735, 'text'=>'下營區'];
        $area[15][] = ['id'=>736, 'text'=>'柳營區'];
        $area[15][] = ['id'=>737, 'text'=>'鹽水區'];
        $area[15][] = ['id'=>741, 'text'=>'善化區'];
        $area[15][] = ['id'=>742, 'text'=>'大內區'];
        $area[15][] = ['id'=>743, 'text'=>'山上區'];
        $area[15][] = ['id'=>744, 'text'=>'新市區'];
        $area[15][] = ['id'=>745, 'text'=>'安定區'];

        $area[16][] = ['id'=>800, 'text'=>'新興區'];
        $area[16][] = ['id'=>801, 'text'=>'前金區'];
        $area[16][] = ['id'=>802, 'text'=>'苓雅區'];
        $area[16][] = ['id'=>803, 'text'=>'鹽埕區'];
        $area[16][] = ['id'=>804, 'text'=>'鼓山區'];
        $area[16][] = ['id'=>805, 'text'=>'旗津區'];
        $area[16][] = ['id'=>806, 'text'=>'前鎮區'];
        $area[16][] = ['id'=>807, 'text'=>'三民區'];
        $area[16][] = ['id'=>811, 'text'=>'楠梓區'];
        $area[16][] = ['id'=>812, 'text'=>'小港區'];
        $area[16][] = ['id'=>813, 'text'=>'左營區'];
        $area[16][] = ['id'=>814, 'text'=>'仁武區'];
        $area[16][] = ['id'=>815, 'text'=>'大社區'];
        $area[16][] = ['id'=>820, 'text'=>'岡山區'];
        $area[16][] = ['id'=>821, 'text'=>'路竹區'];
        $area[16][] = ['id'=>822, 'text'=>'阿蓮區'];
        $area[16][] = ['id'=>823, 'text'=>'田寮鄉'];
        $area[16][] = ['id'=>824, 'text'=>'燕巢區'];
        $area[16][] = ['id'=>825, 'text'=>'橋頭區'];
        $area[16][] = ['id'=>826, 'text'=>'梓官區'];
        $area[16][] = ['id'=>827, 'text'=>'彌陀區'];
        $area[16][] = ['id'=>828, 'text'=>'永安區'];
        $area[16][] = ['id'=>829, 'text'=>'湖內鄉'];
        $area[16][] = ['id'=>830, 'text'=>'鳳山區'];
        $area[16][] = ['id'=>831, 'text'=>'大寮區'];
        $area[16][] = ['id'=>832, 'text'=>'林園區'];
        $area[16][] = ['id'=>833, 'text'=>'鳥松區'];
        $area[16][] = ['id'=>840, 'text'=>'大樹區'];
        $area[16][] = ['id'=>842, 'text'=>'旗山區'];
        $area[16][] = ['id'=>843, 'text'=>'美濃區'];
        $area[16][] = ['id'=>844, 'text'=>'六龜區'];
        $area[16][] = ['id'=>845, 'text'=>'內門區'];
        $area[16][] = ['id'=>846, 'text'=>'杉林區'];
        $area[16][] = ['id'=>847, 'text'=>'甲仙區'];
        $area[16][] = ['id'=>848, 'text'=>'桃源區'];
        $area[16][] = ['id'=>849, 'text'=>'那瑪夏區'];
        $area[16][] = ['id'=>851, 'text'=>'茂林區'];
        $area[16][] = ['id'=>852, 'text'=>'茄萣區'];

        $area[17][] = ['id'=>900, 'text'=>'屏東市'];
        $area[17][] = ['id'=>901, 'text'=>'三地門'];
        $area[17][] = ['id'=>902, 'text'=>'霧臺鄉'];
        $area[17][] = ['id'=>903, 'text'=>'瑪家鄉'];
        $area[17][] = ['id'=>904, 'text'=>'九如鄉'];
        $area[17][] = ['id'=>905, 'text'=>'里港鄉'];
        $area[17][] = ['id'=>906, 'text'=>'高樹鄉'];
        $area[17][] = ['id'=>907, 'text'=>'鹽埔鄉'];
        $area[17][] = ['id'=>908, 'text'=>'長治鄉'];
        $area[17][] = ['id'=>909, 'text'=>'麟洛鄉'];
        $area[17][] = ['id'=>911, 'text'=>'竹田鄉'];
        $area[17][] = ['id'=>912, 'text'=>'內埔鄉'];
        $area[17][] = ['id'=>913, 'text'=>'萬丹鄉'];
        $area[17][] = ['id'=>920, 'text'=>'潮州鎮'];
        $area[17][] = ['id'=>921, 'text'=>'泰武鄉'];
        $area[17][] = ['id'=>922, 'text'=>'來義鄉'];
        $area[17][] = ['id'=>923, 'text'=>'萬巒鄉'];
        $area[17][] = ['id'=>924, 'text'=>'崁頂鄉'];
        $area[17][] = ['id'=>925, 'text'=>'新埤鄉'];
        $area[17][] = ['id'=>926, 'text'=>'南州鄉'];
        $area[17][] = ['id'=>927, 'text'=>'林邊鄉'];
        $area[17][] = ['id'=>928, 'text'=>'東港鎮'];
        $area[17][] = ['id'=>929, 'text'=>'琉球鄉'];
        $area[17][] = ['id'=>931, 'text'=>'佳冬鄉'];
        $area[17][] = ['id'=>932, 'text'=>'新園鄉'];
        $area[17][] = ['id'=>940, 'text'=>'枋寮鄉'];
        $area[17][] = ['id'=>941, 'text'=>'枋山鄉'];
        $area[17][] = ['id'=>942, 'text'=>'春日鄉'];
        $area[17][] = ['id'=>943, 'text'=>'獅子鄉'];
        $area[17][] = ['id'=>944, 'text'=>'車城鄉'];
        $area[17][] = ['id'=>945, 'text'=>'牡丹鄉'];
        $area[17][] = ['id'=>946, 'text'=>'恆春鎮'];
        $area[17][] = ['id'=>947, 'text'=>'滿州鄉'];

        $area[18][] = ['id'=>950, 'text'=>'臺東市'];
        $area[18][] = ['id'=>951, 'text'=>'綠島鄉'];
        $area[18][] = ['id'=>952, 'text'=>'蘭嶼鄉'];
        $area[18][] = ['id'=>953, 'text'=>'延平鄉'];
        $area[18][] = ['id'=>954, 'text'=>'卑南鄉'];
        $area[18][] = ['id'=>955, 'text'=>'鹿野鄉'];
        $area[18][] = ['id'=>956, 'text'=>'關山鎮'];
        $area[18][] = ['id'=>957, 'text'=>'海端鄉'];
        $area[18][] = ['id'=>958, 'text'=>'池上鄉'];
        $area[18][] = ['id'=>959, 'text'=>'東河鄉'];
        $area[18][] = ['id'=>961, 'text'=>'成功鎮'];
        $area[18][] = ['id'=>962, 'text'=>'長濱鄉'];
        $area[18][] = ['id'=>963, 'text'=>'太麻里鄉'];
        $area[18][] = ['id'=>964, 'text'=>'金峰鄉'];
        $area[18][] = ['id'=>965, 'text'=>'大武鄉'];
        $area[18][] = ['id'=>966, 'text'=>'達仁鄉'];

        $area[19][] = ['id'=>970, 'text'=>'花蓮市'];
        $area[19][] = ['id'=>971, 'text'=>'新城鄉'];
        $area[19][] = ['id'=>972, 'text'=>'秀林鄉'];
        $area[19][] = ['id'=>973, 'text'=>'吉安鄉'];
        $area[19][] = ['id'=>974, 'text'=>'壽豐鄉'];
        $area[19][] = ['id'=>975, 'text'=>'鳳林鎮'];
        $area[19][] = ['id'=>976, 'text'=>'光復鄉'];
        $area[19][] = ['id'=>977, 'text'=>'豐濱鄉'];
        $area[19][] = ['id'=>978, 'text'=>'瑞穗鄉'];
        $area[19][] = ['id'=>979, 'text'=>'萬榮鄉'];
        $area[19][] = ['id'=>981, 'text'=>'玉里鎮'];
        $area[19][] = ['id'=>982, 'text'=>'卓溪鄉'];
        $area[19][] = ['id'=>983, 'text'=>'富里鄉'];

        $area[20][] = ['id'=>890, 'text'=>'金沙鎮'];
        $area[20][] = ['id'=>891, 'text'=>'金湖鎮'];
        $area[20][] = ['id'=>892, 'text'=>'金寧鄉'];
        $area[20][] = ['id'=>893, 'text'=>'金城鎮'];
        $area[20][] = ['id'=>894, 'text'=>'烈嶼鄉'];
        $area[20][] = ['id'=>896, 'text'=>'烏坵鄉'];
        
        $area[21][] = ['id'=>209, 'text'=>'南竿鄉'];
        $area[21][] = ['id'=>210, 'text'=>'北竿鄉'];
        $area[21][] = ['id'=>211, 'text'=>'莒光鄉'];
        $area[21][] = ['id'=>212, 'text'=>'東引鄉'];
        
        $area[22][] = ['id'=>880, 'text'=>'馬公市'];
        $area[22][] = ['id'=>881, 'text'=>'西嶼鄉'];
        $area[22][] = ['id'=>882, 'text'=>'望安鄉'];
        $area[22][] = ['id'=>883, 'text'=>'七美鄉'];
        $area[22][] = ['id'=>884, 'text'=>'白沙鄉'];
        $area[22][] = ['id'=>885, 'text'=>'湖西鄉'];
        
        $area[23][] = ['id'=>817, 'text'=>'東沙'];
        $area[23][] = ['id'=>819, 'text'=>'南沙'];
        return response()->json($area[$city_id], 200, [], JSON_PRETTY_PRINT);
    }

    public function bank()
    {
        $array["004"] = array('code'=>'004', 'name'=>'台灣銀行', 'sort'=>1);
        $array["005"] = array('code'=>'005', 'name'=>'土地銀行', 'sort'=>2);
        $array["006"] = array('code'=>'006', 'name'=>'合作金庫銀行', 'sort'=>3);
        $array["007"] = array('code'=>'007', 'name'=>'第一銀行', 'sort'=>4);
        $array["008"] = array('code'=>'008', 'name'=>'華南銀行', 'sort'=>5);
        $array["009"] = array('code'=>'009', 'name'=>'彰化銀行', 'sort'=>6);
        $array["011"] = array('code'=>'011', 'name'=>'上海銀行', 'sort'=>7);
        $array["012"] = array('code'=>'012', 'name'=>'台北富邦銀行', 'sort'=>8);
        $array["013"] = array('code'=>'013', 'name'=>'國泰世華銀行', 'sort'=>9);
        $array["016"] = array('code'=>'016', 'name'=>'高雄銀行', 'sort'=>10);
        $array["017"] = array('code'=>'017', 'name'=>'兆豐國際商銀', 'sort'=>11);
        $array["018"] = array('code'=>'018', 'name'=>'農業金庫', 'sort'=>12);
        $array["021"] = array('code'=>'021', 'name'=>'花旗(台灣)商銀', 'sort'=>13);
        $array["022"] = array('code'=>'022', 'name'=>'美國銀行台北分行', 'sort'=>14);
        $array["025"] = array('code'=>'025', 'name'=>'菲律賓首都銀行', 'sort'=>15);
        $array["039"] = array('code'=>'039', 'name'=>'澳盛(台灣)商銀', 'sort'=>16);
        $array["040"] = array('code'=>'040', 'name'=>'中華開發', 'sort'=>17);
        $array["048"] = array('code'=>'048', 'name'=>'台灣工業銀行', 'sort'=>18);
        $array["050"] = array('code'=>'050', 'name'=>'台灣企銀', 'sort'=>19);
        $array["052"] = array('code'=>'052', 'name'=>'渣打國際商銀', 'sort'=>20);
        $array["053"] = array('code'=>'053', 'name'=>'台中商銀', 'sort'=>21);
        $array["054"] = array('code'=>'054', 'name'=>'京城商銀', 'sort'=>22);
        $array["072"] = array('code'=>'072', 'name'=>'德商德意志銀行', 'sort'=>23);
        $array["075"] = array('code'=>'075', 'name'=>'東亞銀行', 'sort'=>24);
        $array["081"] = array('code'=>'081', 'name'=>'匯豐(台灣)商銀', 'sort'=>25);
        $array["085"] = array('code'=>'085', 'name'=>'新僑銀行', 'sort'=>26);
        $array["101"] = array('code'=>'101', 'name'=>'瑞興銀行', 'sort'=>27);
        $array["102"] = array('code'=>'102', 'name'=>'華泰銀行', 'sort'=>28);
        $array["103"] = array('code'=>'103', 'name'=>'新光商業銀行', 'sort'=>29);
        $array["104"] = array('code'=>'104', 'name'=>'台北五信', 'sort'=>30);
        $array["108"] = array('code'=>'108', 'name'=>'陽信銀行', 'sort'=>31);
        $array["114"] = array('code'=>'114', 'name'=>'基隆一信', 'sort'=>32);
        $array["115"] = array('code'=>'115', 'name'=>'基隆二信', 'sort'=>33);
        $array["118"] = array('code'=>'118', 'name'=>'板信銀行', 'sort'=>34);
        $array["119"] = array('code'=>'119', 'name'=>'淡水一信', 'sort'=>35);
        $array["120"] = array('code'=>'120', 'name'=>'淡水信合社', 'sort'=>36);
        $array["124"] = array('code'=>'124', 'name'=>'宜蘭信合社', 'sort'=>37);
        $array["127"] = array('code'=>'127', 'name'=>'桃園信合社', 'sort'=>38);
        $array["130"] = array('code'=>'130', 'name'=>'新竹一信', 'sort'=>39);
        $array["132"] = array('code'=>'132', 'name'=>'新竹三信', 'sort'=>40);
        $array["146"] = array('code'=>'146', 'name'=>'台中二信', 'sort'=>41);
        $array["147"] = array('code'=>'147', 'name'=>'三信銀行', 'sort'=>42);
        $array["158"] = array('code'=>'158', 'name'=>'彰化一信', 'sort'=>43);
        $array["161"] = array('code'=>'161', 'name'=>'彰化五信', 'sort'=>44);
        $array["162"] = array('code'=>'162', 'name'=>'彰化六信', 'sort'=>45);
        $array["163"] = array('code'=>'163', 'name'=>'彰化十信', 'sort'=>46);
        $array["165"] = array('code'=>'165', 'name'=>'鹿港信合社', 'sort'=>47);
        $array["178"] = array('code'=>'178', 'name'=>'嘉義三信', 'sort'=>48);
        $array["188"] = array('code'=>'188', 'name'=>'台南三信', 'sort'=>49);
        $array["204"] = array('code'=>'204', 'name'=>'高雄三信', 'sort'=>50);
        $array["215"] = array('code'=>'215', 'name'=>'花蓮一信', 'sort'=>51);
        $array["216"] = array('code'=>'216', 'name'=>'花蓮二信', 'sort'=>52);
        $array["222"] = array('code'=>'222', 'name'=>'澎湖一信', 'sort'=>53);
        $array["223"] = array('code'=>'223', 'name'=>'澎湖二信', 'sort'=>54);
        $array["224"] = array('code'=>'224', 'name'=>'金門信合社', 'sort'=>55);
        $array["380"] = array('code'=>'380', 'name'=>'大陸商中國銀行', 'sort'=>56);
        $array["381"] = array('code'=>'381', 'name'=>'大陸商交通銀行', 'sort'=>57);
        $array["512"] = array('code'=>'512', 'name'=>'雲林漁會', 'sort'=>58);
        $array["515"] = array('code'=>'515', 'name'=>'嘉義漁會', 'sort'=>59);
        $array["517"] = array('code'=>'517', 'name'=>'南市區漁會', 'sort'=>60);
        $array["518"] = array('code'=>'518', 'name'=>'南縣漁會', 'sort'=>61);
        $array["520"] = array('code'=>'520', 'name'=>'小港漁會', 'sort'=>62);
        $array["521"] = array('code'=>'521', 'name'=>'高雄縣漁會', 'sort'=>63);
        $array["523"] = array('code'=>'523', 'name'=>'枋寮區漁會', 'sort'=>64);
        $array["524"] = array('code'=>'524', 'name'=>'新港漁會', 'sort'=>65);
        $array["525"] = array('code'=>'525', 'name'=>'澎湖區漁會', 'sort'=>66);
        $array["605"] = array('code'=>'605', 'name'=>'高雄市高雄地區農會', 'sort'=>67);
        $array["612"] = array('code'=>'612', 'name'=>'臺中縣農會', 'sort'=>68);
        $array["613"] = array('code'=>'613', 'name'=>'名間農會', 'sort'=>69);
        $array["614"] = array('code'=>'614', 'name'=>'彰化區農會', 'sort'=>70);
        $array["616"] = array('code'=>'616', 'name'=>'雲林區農會', 'sort'=>71);
        $array["617"] = array('code'=>'617', 'name'=>'嘉義區農會', 'sort'=>72);
        $array["618"] = array('code'=>'618', 'name'=>'台南區農會', 'sort'=>73);
        $array["619"] = array('code'=>'619', 'name'=>'高雄區農會', 'sort'=>74);
        $array["620"] = array('code'=>'620', 'name'=>'南區農漁會', 'sort'=>75);
        $array["621"] = array('code'=>'621', 'name'=>'花蓮區農會', 'sort'=>76);
        $array["622"] = array('code'=>'622', 'name'=>'台東區農會', 'sort'=>77);
        $array["624"] = array('code'=>'624', 'name'=>'澎湖縣農會', 'sort'=>78);
        $array["625"] = array('code'=>'625', 'name'=>'台中市農會', 'sort'=>79);
        $array["627"] = array('code'=>'627', 'name'=>'連江縣農會', 'sort'=>80);
        $array["700"] = array('code'=>'700', 'name'=>'中華郵政', 'sort'=>81);
        $array["803"] = array('code'=>'803', 'name'=>'聯邦銀行', 'sort'=>82);
        $array["805"] = array('code'=>'805', 'name'=>'遠東銀行', 'sort'=>83);
        $array["806"] = array('code'=>'806', 'name'=>'元大銀行', 'sort'=>84);
        $array["807"] = array('code'=>'807', 'name'=>'永豐商業銀行', 'sort'=>85);
        $array["808"] = array('code'=>'808', 'name'=>'玉山銀行', 'sort'=>86);
        $array["809"] = array('code'=>'809', 'name'=>'凱基商業銀行', 'sort'=>87);
        $array["810"] = array('code'=>'810', 'name'=>'星展銀行', 'sort'=>88);
        $array["812"] = array('code'=>'812', 'name'=>'台新銀行', 'sort'=>89);
        $array["814"] = array('code'=>'814', 'name'=>'大眾銀行', 'sort'=>90);
        $array["815"] = array('code'=>'815', 'name'=>'日盛銀行', 'sort'=>91);
        $array["816"] = array('code'=>'816', 'name'=>'安泰銀行', 'sort'=>92);
        $array["822"] = array('code'=>'822', 'name'=>'中國信託', 'sort'=>93);
        $array["901"] = array('code'=>'901', 'name'=>'大里農會', 'sort'=>94);
        $array["903"] = array('code'=>'903', 'name'=>'汐止農會', 'sort'=>95);
        $array["904"] = array('code'=>'904', 'name'=>'新莊農會', 'sort'=>96);
        $array["910"] = array('code'=>'910', 'name'=>'桃竹農漁會', 'sort'=>97);
        $array["912"] = array('code'=>'912', 'name'=>'冬山農會', 'sort'=>98);
        $array["916"] = array('code'=>'916', 'name'=>'草屯農會', 'sort'=>99);
        $array["922"] = array('code'=>'922', 'name'=>'台南市台南地區農會', 'sort'=>100);
        $array["928"] = array('code'=>'928', 'name'=>'板橋農會', 'sort'=>101);
        $array["951"] = array('code'=>'951', 'name'=>'北區農漁會', 'sort'=>102);
        $array["952"] = array('code'=>'952', 'name'=>'農漁會南區中心', 'sort'=>103);
        $array["954"] = array('code'=>'954', 'name'=>'中區農漁會', 'sort'=>104);
    }

    public function country()
    {
        $array['886'] = array('code' => '886', 'name' => '台灣', 'length' => array(10), 'hint' => '手機號碼(10碼)', 'sort' => 1);
        $array['86']  = array('code' => '86',  'name' => '中國', 'length' => array(11), 'hint' => '手機號碼(11碼)', 'sort' => 2);
        $array['1']   = array('code' => '1',   'name' => '美加', 'length' => array(10), 'hint' => '手機號碼(10碼)', 'sort' => 3);
        $array['852'] = array('code' => '852', 'name' => '香港', 'length' => array(8), 'hint' => '手機號碼(8碼)', 'sort' => 4);
        $array['853'] = array('code' => '853', 'name' => '澳門', 'length' => array(8), 'hint' => '手機號碼(8碼)',  'sort' => 5);
    }
}
